version: "3.0"

services:
  acp:
    container_name: quickstart-acp
    restart: always
    image: docker.cloudentity.io/acp:${ACP_VERSION}
    networks:
      default:
        aliases:
        - authorization.cloudentity.com
        - test-docker
    ports:
      - 8443:8443
    volumes:
      - ./data/acp_cert.pem:/acp_cert.pem
      - ./data/acp_key.pem:/acp_key.pem
      - ./data/ca.pem:/acp_ca.pem
    environment:
      - FEATURES_SWAGGER_UI=true
      - FEATURES_INTEGRATION_ENDPOINTS=true
      - FEATURES_SYSTEM_OPENBANKING_CONSENTS_MANAGEMENT=true
      - FEATURES_OPENBANKING_DOMESTIC_PAYMENT_CONSENTS=true
      - FEATURES_SYSTEM_CLIENTS_MANAGEMENT=true
      - FEATURES_OPENBANKING_BRASIL_CONSENTS=true
      - FEATURES_OPENBANKING_BRASIL_PAYMENTS=true
      - FEATURES_DEV_MODE=true
      - FEATURES_SCRIPTS=true
      - FEATURES_CIBA=true
      - FEATURES_FDX=true
      - SERVER_MTLS_URL=https://test-docker:8443
      - SERVER_URL=${ACP_URL}
      - LOGGING_LEVEL=debug
      - SERVER_HTTP_LOGS=true
      - SERVER_DISABLE_CSRF=true
      - SERVER_DO_NOT_PRINT_AUDIT_LOGS_FOR_STATIC_FILES=true
      - CLIENT_ROOT_CA=/acp_ca.pem
      - REDIS_ENABLED=true
      - REDIS_ADDRESS=redis:6379
    command:
      - server
      - start
      - --config
      - /config/reference.yaml
      - --sql.url
      - postgres://root@crdb:26257/defaultdb?sslmode=disable
      - --secret.key
      - KNEcLGdDqpwrXDubqPgDSUkMMsLPXaHh
      - --server.cert.path
      - /acp_cert.pem
      - --server.key.path
      - /acp_key.pem
      - --demo
      - --create-default-tenant
    depends_on:
      - crdb
      - redis

  crdb:
    container_name: quickstart-crdb
    image: cockroachdb/cockroach:v21.2.3
    restart: always
    ports:
      - 26258:26257
      - 8082:8080
    command: start-single-node --insecure
    volumes:
      - crdb:/cockroach/cockroach-data"

  redis:
    container_name: quickstart-redis
    image: redislabs/redisearch:2.4.8
    restart: on-failure
    command: redis-server /usr/local/etc/redis/redis.conf --loadmodule /usr/lib/redis/modules/redisearch.so
    volumes:
      - ./mount/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6380:6379

  runner:
    container_name: quickstart-runner
    image: quickstart-runner
    command: /bin/sh
    tty: true
    volumes:
      - .:/code

volumes:
  crdb:
